source 'https://rubygems.org'

# rails
gem 'rails', '~> 4.2.6'

# use postgresql as the database for Active Record
gem 'pg'

gem 'sinatra', '1.1.0'
gem 'passenger', '>= 5.0.15'


gem 'net-ssh'
gem 'sprockets', '2.12.3'


# error tracking
gem 'rollbar'

# assets
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails', '~> 3.1.1'
# -------------------------------
# trick to use sass 3.3
gem 'sass', '~> 3.4.19'
gem 'sass-rails', '~> 5.0.4'
# -------------------------------
gem 'coffee-rails', '~> 4.1.0'
gem 'font-awesome-sass', '~> 4.2.0'

# slim
gem 'slim-rails'

# forms
gem 'simple_form', '~> 3.0.2'

# meta tags
gem 'meta-tags', '~> 2.0.0'

# static pages
gem 'high_voltage', '~> 2.2.1'


# spring speeds up development by keeping your application running in the background. Read more: https://github.com/jonleighton/spring
group :development do
  gem 'spring'
  gem 'start', '0.1.1'
  gem 'better_errors',           '~> 1.0.1'
  gem 'binding_of_caller',       '~> 0.7.1'
  gem 'xray-rails'
  # gem 'sprockets_better_errors', '~> 0.0.2'
end

# authentication
gem 'devise'
gem 'devise_invitable'

# access levels
gem 'cancancan', '~> 1.9'


# friendly urls
gem 'friendly_id', '~> 5.0.4'

# custom validation for urls
gem 'validate_url'

# keeps session in active record so session can be bigger than 4kb
gem 'activerecord-session_store', '~> 0.1.0'

gem 'kaminari', '0.16.1'

group :test, :development do
  # specs
  gem 'rspec-rails', '~> 3.0.2'

  # interactive debug
  gem 'pry-rails',   '~> 0.3.2'

  # factories
  gem 'factory_girl_rails', '~> 4.4.0'

  # javascript specs
  gem 'jasmine-rails', '~> 0.6.0'

  # jquery for javascript specs
  gem 'jasmine-jquery-rails', '2.0.2'
end

group :test do

  # test coverage
  gem 'simplecov',  '~> 0.8.2', require: false

  # feature specs
  gem 'launchy',    '~> 2.4.2'
end


gem 'redactor-rails', '~> 0.4.5'
gem 'sitemap_generator', '~> 5.0.5'

gem 'mini_magick', '~> 3.7.0'
gem 'carrierwave', '~> 0.10.0'
gem 'fog', '~> 1.29.0'
gem 'roadie', '~> 2.4.3'
gem 'remotipart', '~> 1.2.1'

gem 'wrgem'

gem 'rails_12factor', group: :production
gem 'rufus-scheduler', '~> 3.0.3', group: :production
gem 'rack-timeout', '~> 0.0.4'

gem 'gibbon', '~> 1.2.0'
